"use client";

import Link from "next/link";
import { ArrowLeft, Download, DatabaseZap, TerminalSquare, TrendingUp } from "lucide-react";
import Footer from "../../../components/Footer";
import PageLoader from "../../../components/PageLoader";
import { useLang } from "../../../components/LanguageContext";

const translations = {
  en: {
    backHome: "Back to Home",
    heroDesc: "Build scripts to process and automate pipelines. Show skills in Python, Node, and data efficiency. Drive enterprise workflows with intelligent automation logic.",
    registerTrack: "Register Track",
    downloadRulebook: "Download Rulebook",

    focus: [
      {
        title: "Robust Scripting",
        desc: "Write clean, modular, and fault-tolerant scripts. Deal with error handling, API rate limits, and unstructured datasets efficiently.",
      },
      {
        title: "Pipeline Engineering",
        desc: "Design logical workflows that transform raw inputs into structured outputs quickly, reducing manual labor processing times drastically.",
      },
      {
        title: "Scaling & Optimization",
        desc: "It's not just about getting it to work once; it's about processing 1,000,000 rows as efficiently as 100 rows. Optimize your logic.",
      },
    ],

    requirementsHeading: "Final Submission (Mandatory Outputs)",
    requirementsSubheading: "Participants must submit the following four components, compressed into a single .zip file. Non-compliance with formatting requirements will result in point deductions.",
    requirements: [
      {
        title: "A. Pipeline Output (.csv File)",
        desc: "The final output generated by the automation script execution. Filename: Daily_Action_Report.csv. Mandatory Format (2 Columns Only):",
        bullets: [
          "Item_ID: Unique ID for raw materials/inventory.",
          "Action_Status: The final inventory status. Must be populated with one of four options:",
          "- Safe: Stock levels are sufficient for operations.",
          "- Restock: Stock has reached the minimum threshold; reordering is required.",
          "- Invalid Data: Raw data row is corrupted, incorrectly formatted, or the Item_ID is unregistered.",
          "- Anomaly: A logical discrepancy exists between sales logs and physical warehouse stock.",
        ],
      },
      {
        title: "B. Executable Code (.py or .ipynb)",
        desc: "The source code script that executes the entire data processing workflow (Zero Human Intervention). Mandatory Requirement: The code must include Code Comments explaining logic for:",
        bullets: [
          "Data Ingestion: The process of retrieving and reading raw data.",
          "Data Cleansing: Logic for handling corrupted, incorrectly formatted, or missing data.",
          "Calculation: Mathematical formulas for calculating stock inflows and outflows.",
          "Anomaly Logic: Business rules and logic used to detect inventory mismatches.",
        ],
      },
      {
        title: "C. System Analysis & Design Document (.pdf)",
        desc: "A technical document justifying the system architecture design. It must include the following four points:",
        bullets: [
          "Problem Analysis: Identification of current MSME operational weaknesses.",
          "System Solution: A narrative explanation of the logic and business rules utilized within the script.",
          "System Requirements: Specification of Functional and Non-Functional Requirements.",
        ],
      },
      {
        title: "D. Execution Instructions (README)",
        desc: "A brief guide for the judging panel to conduct testing and run the automation script on the committee's computer. Format: Plain text (Markdown or TXT). Content:",
        bullets: [
          "Dependencies/Prerequisites: A list of libraries or packages that must be installed (e.g., pandas, numpy, or requirements.txt).",
          "Environment: Specifications of the programming language version or local database used (e.g., Python 3.10, MySQL 8.0).",
          "Execution Steps: A clear sequence of commands to run the script until it generates the Daily_Action_Report.csv file.",
        ],
      },
    ],
  },

  id: {
    backHome: "Kembali ke Beranda",
    heroDesc: "Bangun skrip untuk memproses dan mengotomasi pipeline. Tunjukkan kemampuanmu dalam Python, Node, dan efisiensi data. Dorong alur kerja perusahaan dengan logika otomasi yang cerdas.",
    registerTrack: "Daftar Trek",
    downloadRulebook: "Unduh Buku Panduan",

    focus: [
      {
        title: "Scripting yang Andal",
        desc: "Tulis skrip yang bersih, modular, dan toleran terhadap kesalahan. Tangani error handling, batas rate API, dan dataset tidak terstruktur secara efisien.",
      },
      {
        title: "Rekayasa Pipeline",
        desc: "Rancang alur kerja yang logis untuk mengubah input mentah menjadi output terstruktur dengan cepat, sehingga secara drastis mengurangi waktu pemrosesan manual.",
      },
      {
        title: "Skalabilitas & Optimasi",
        desc: "Bukan hanya soal membuatnya berjalan sekali; ini soal memproses 1.000.000 baris seefisien 100 baris. Optimalkan logikamu.",
      },
    ],

    requirementsHeading: "Pengumpulan Akhir (Output Wajib)",
    requirementsSubheading: "Peserta wajib mengumpulkan empat komponen berikut dalam satu file .zip. Ketidakpatuhan terhadap persyaratan format akan mengakibatkan pengurangan poin.",
    requirements: [
      {
        title: "A. Output Pipeline (File .csv)",
        desc: "Output akhir yang dihasilkan dari eksekusi skrip otomasi. Nama file: Daily_Action_Report.csv. Format Wajib (2 Kolom Saja):",
        bullets: [
          "Item_ID: ID unik untuk bahan baku/inventaris.",
          "Action_Status: Status inventaris akhir. Wajib diisi dengan satu dari empat opsi berikut:",
          "- Safe (Aman): Jumlah stok mencukupi untuk operasional.",
          "- Restock (Restock): Stok telah mencapai batas minimum; pemesanan ulang diperlukan.",
          "- Invalid Data (Data Tidak Valid): Baris data mentah rusak, berformat salah, atau Item_ID tidak terdaftar.",
          "- Anomaly (Anomali): Terdapat ketidaksesuaian logis antara log penjualan dan stok gudang fisik.",
        ],
      },
      {
        title: "B. Kode Eksekutabel (.py atau .ipynb)",
        desc: "Skrip kode sumber yang menjalankan seluruh alur pemrosesan data (Tanpa Intervensi Manusia). Persyaratan Wajib: Kode harus menyertakan Komentar Kode yang menjelaskan logika untuk:",
        bullets: [
          "Pengambilan Data (Data Ingestion): Proses pengambilan dan pembacaan data mentah.",
          "Pembersihan Data (Data Cleansing): Logika untuk menangani data yang rusak, berformat salah, atau hilang.",
          "Perhitungan (Calculation): Rumus matematis untuk menghitung arus masuk dan keluar stok.",
          "Logika Anomali (Anomaly Logic): Aturan dan logika bisnis yang digunakan untuk mendeteksi ketidaksesuaian inventaris.",
        ],
      },
      {
        title: "C. Dokumen Analisis & Desain Sistem (.pdf)",
        desc: "Dokumen teknis yang membenarkan desain arsitektur sistem. Dokumen ini harus mencakup empat poin berikut:",
        bullets: [
          "Analisis Masalah: Identifikasi kelemahan operasional UMKM saat ini.",
          "Solusi Sistem: Penjelasan naratif tentang logika dan aturan bisnis yang digunakan dalam skrip.",
          "Persyaratan Sistem: Spesifikasi Persyaratan Fungsional dan Non-Fungsional.",
        ],
      },
      {
        title: "D. Instruksi Eksekusi (README)",
        desc: "Panduan singkat bagi panel juri untuk melakukan pengujian dan menjalankan skrip otomasi di komputer panitia. Format: Teks biasa (Markdown atau TXT). Isi:",
        bullets: [
          "Dependensi/Prasyarat: Daftar pustaka atau paket yang harus diinstal (misalnya, pandas, numpy, atau requirements.txt).",
          "Lingkungan: Spesifikasi versi bahasa pemrograman atau basis data lokal yang digunakan (misalnya, Python 3.10, MySQL 8.0).",
          "Langkah Eksekusi: Urutan perintah yang jelas untuk menjalankan skrip hingga menghasilkan file Daily_Action_Report.csv.",
        ],
      },
    ],
  },
};

export default function DataAutomationTrackPage() {
  const { lang } = useLang();
  const tx = translations[lang];

  return (
    <div className="min-h-screen bg-[#050814] text-white font-sans selection:bg-blue-500 selection:text-white overflow-x-hidden">

      <PageLoader />

      {/* Navigation */}
      <nav className="p-6 w-full absolute top-0 z-50">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <Link href="/" className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors text-sm font-light">
            <ArrowLeft className="w-4 h-4" /> {tx.backHome}
          </Link>
          <img src="/logo-techsprint-2026.png" alt="3IN1 Tech Sprint 2026" className="h-20 w-auto object-contain" />
        </div>
      </nav>

      {/* Hero Section */}
      <section className="bg-gradient-to-b from-black via-[#050814] to-[#0a0f24] relative pt-40 pb-20 overflow-hidden flex flex-col items-center justify-center min-h-[50vh]">
        <div className="relative z-10 text-center px-6 pt-10 mx-auto">
          <h1 className="text-5xl md:text-[200px] font-bold tracking-[-0.1em] bg-gradient-to-b from-blue-500 to-blue-950/5 bg-clip-text text-transparent mb-6">
            Data Automation
          </h1>
          <p className="text-gray-400 text-lg md:text-xl font-light leading-relaxed max-w-2xl mx-auto">
            {tx.heroDesc}
          </p>
          <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link href="/register" className="px-8 py-3 rounded-full bg-blue-600 text-white font-medium hover:bg-blue-500 transition-colors">
              {tx.registerTrack}
            </Link>
            <a href="/booklet/DATA-AUTOMATION-TECH-SPRINT-2026-BOOKLET-PARTICIPANT.pdf" target="_blank" rel="noopener noreferrer" className="relative group p-[2px] rounded-full bg-gradient-to-r from-blue-600 via-blue-500 to-blue-400 transition-all inline-flex">
              <span className="flex items-center gap-2 px-8 py-3 bg-black text-white font-medium rounded-full w-full h-full group-hover:bg-black/50 transition-colors duration-300">
                <Download className="w-4 h-4" /> {tx.downloadRulebook}
              </span>
            </a>
          </div>
        </div>
      </section>

      {/* Key Focus */}
      <section className="py-24 bg-gradient-to-b from-[#0a0f24] via-[#050814] to-black">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-12">
          {/* Card 1 */}
          <div className="flex flex-col items-center text-center p-8 bg-gradient-to-b from-blue-500/5 via-[#050814] to-[#0a0f24] rounded-3xl hover:bg-white/[0.04] transition-colors">
            <div className="w-16 h-16 bg-gradient-to-b from-blue-500/20 via-blue-500/5 to-blue-500/20 text-blue-400 rounded-2xl flex items-center justify-center mb-6">
              <TerminalSquare className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-medium text-white mb-3">{tx.focus[0].title}</h3>
            <p className="text-gray-400 font-light text-sm leading-relaxed">{tx.focus[0].desc}</p>
          </div>

          {/* Card 2 */}
          <div className="flex flex-col items-center text-center p-8 bg-gradient-to-b from-blue-500/5 via-[#050814] to-[#0a0f24] rounded-3xl hover:bg-white/[0.04] transition-colors">
            <div className="w-16 h-16 bg-gradient-to-b from-purple-500/20 via-purple-500/5 to-purple-500/20 text-purple-400 rounded-2xl flex items-center justify-center mb-6">
              <DatabaseZap className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-medium text-white mb-3">{tx.focus[1].title}</h3>
            <p className="text-gray-400 font-light text-sm leading-relaxed">{tx.focus[1].desc}</p>
          </div>

          {/* Card 3 */}
          <div className="flex flex-col items-center text-center p-8 bg-gradient-to-b from-blue-500/5 via-[#050814] to-[#0a0f24] rounded-3xl hover:bg-white/[0.04] transition-colors">
            <div className="w-16 h-16 bg-gradient-to-b from-emerald-500/20 via-emerald-500/5 to-emerald-500/20 text-emerald-400 rounded-2xl flex items-center justify-center mb-6">
              <TrendingUp className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-medium text-white mb-3">{tx.focus[2].title}</h3>
            <p className="text-gray-400 font-light text-sm leading-relaxed">{tx.focus[2].desc}</p>
          </div>
        </div>
      </section>

      {/* Track Requirements */}
      <section className="py-24 bg-gradient-to-b from-black via-[#050814] to-[#0a0f24]">
        <div className="max-w-5xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-semibold md:text-5xl font-light text-white mb-4">{tx.requirementsHeading}</h2>
            <p className="text-gray-400 font-light max-w-3xl mx-auto leading-relaxed">{tx.requirementsSubheading}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
            {tx.requirements.map((req, idx) => (
              <div key={idx} className="relative flex flex-col bg-white/[0.02] rounded-3xl p-8 transition-transform duration-300 group hover:shadow-[0_0_20px_rgba(59,130,246,0.15)] h-full">
                <h3 className="text-xl font-semibold mb-3 text-blue-400">{req.title}</h3>
                <p className="text-gray-300 font-light text-sm mb-4 leading-relaxed">{req.desc}</p>
                <div className="flex flex-col gap-3 flex-1">
                  {req.bullets.map((bullet, bIdx) => (
                    <div key={bIdx} className="flex items-start gap-3 text-sm font-light">
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-2 shrink-0" />
                      <span className="text-gray-400 leading-relaxed">{bullet}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
