import Link from "next/link";
import { ArrowLeft, CheckCircle2, Download, DatabaseZap, TerminalSquare, TrendingUp } from "lucide-react";
import Footer from "../../../components/Footer";
import PageLoader from "../../../components/PageLoader";

export default function DataAutomationTrackPage() {
  const requirements = [
    {
      title: "A. Pipeline Output (.csv File)",
      desc: "The final output generated by the automation script execution. Filename: Daily_Action_Report.csv. Mandatory Format (2 Columns Only):",
      bullets: [
        "Item_ID: Unique ID for raw materials/inventory.",
        "Action_Status: The final inventory status. Must be populated with one of four options:",
        "- Safe: Stock levels are sufficient for operations.",
        "- Restock: Stock has reached the minimum threshold; reordering is required.",
        "- Invalid Data: Raw data row is corrupted, incorrectly formatted, or the Item_ID is unregistered.",
        "- Anomaly: A logical discrepancy exists between sales logs and physical warehouse stock."
      ]
    },
    {
      title: "B. Executable Code (.py or .ipynb)",
      desc: "The source code script that executes the entire data processing workflow (Zero Human Intervention). Mandatory Requirement: The code must include Code Comments explaining logic for:",
      bullets: [
        "Data Ingestion: The process of retrieving and reading raw data.",
        "Data Cleansing: Logic for handling corrupted, incorrectly formatted, or missing data.",
        "Calculation: Mathematical formulas for calculating stock inflows and outflows.",
        "Anomaly Logic: Business rules and logic used to detect inventory mismatches."
      ]
    },
    {
      title: "C. System Analysis & Design Document (.pdf)",
      desc: "A technical document justifying the system architecture design. It must include the following four points:",
      bullets: [
        "Problem Analysis: Identification of current MSME operational weaknesses.",
        "System Solution: A narrative explanation of the logic and business rules utilized within the script.",
        "System Requirements: Specification of Functional and Non-Functional Requirements.",
      ]
    },
    {
      title: "D. Execution Instructions (README)",
      desc: "A brief guide for the judging panel to conduct testing and run the automation script on the committee’s computer. Format: Plain text (Markdown or TXT). Content:",
      bullets: [
        "Dependencies/Prerequisites: A list of libraries or packages that must be installed (e.g., pandas, numpy, or requirements.txt).",
        "Environment: Specifications of the programming language version or local database used (e.g., Python 3.10, MySQL 8.0).",
        "Execution Steps: A clear sequence of commands to run the script until it generates the Daily_Action_Report.csv file."
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-[#050814] text-white font-sans selection:bg-blue-500 selection:text-white overflow-x-hidden">

      <PageLoader />

      {/* Navigation */}
      <nav className="p-6 w-full absolute top-0 z-50">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <Link href="/" className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors text-sm font-light">
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </Link>
          <img src="/logo-techsprint-2026.png" alt="3IN1 Tech Sprint 2026" className="h-20 w-auto object-contain" />
        </div>
      </nav>

      {/* Hero Section */}
      <section className="bg-gradient-to-b from-black via-[#050814] to-[#0a0f24] relative pt-40 pb-20 overflow-hidden flex flex-col items-center justify-center min-h-[50vh]">
        <div className="relative z-10 text-center px-6 pt-10 mx-auto">
          {/* <div className="mx-auto w-20 h-20 bg-blue-500/10 rounded-3xl flex items-center justify-center mb-8">
            <DatabaseZap className="text-blue-400 w-10 h-10" />
          </div> */}
          <h1 className="text-5xl md:text-[200px] font-bold tracking-[-0.1em] bg-gradient-to-b from-blue-500 to-blue-950/5 bg-clip-text text-transparent mb-6">
            Data Automation
          </h1>
          <p className="text-gray-400 text-lg md:text-xl font-light leading-relaxed max-w-2xl mx-auto">
            Build scripts to process and automate pipelines. Show skills in Python, Node, and data efficiency. Drive enterprise workflows with intelligent automation logic.
          </p>
          <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link href="/register" className="px-8 py-3 rounded-full bg-blue-600 text-white font-medium hover:bg-blue-500 transition-colors">
              Register Track
            </Link>
            <a href="/DATA-AUTOMATION-TECH-SPRINT-2026-BOOKLET-PARTICIPANT.pdf" target="_blank" rel="noopener noreferrer" className="relative group p-[2px] rounded-full bg-gradient-to-r from-blue-600 via-blue-500 to-blue-400 transition-all inline-flex">
              <span className="flex items-center gap-2 px-8 py-3 bg-black text-white font-medium rounded-full w-full h-full group-hover:bg-black/50 transition-colors duration-300">
                <Download className="w-4 h-4" /> Download Rulebook
              </span>
            </a>
          </div>
        </div>
      </section>

      {/* What you will learn / Key Focus */}
      <section className="py-24 bg-gradient-to-b from-[#0a0f24] via-[#050814] to-black">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-12">
          <div className="flex flex-col items-center text-center p-8 bg-gradient-to-b from-blue-500/5 via-[#050814] to-[#0a0f24] rounded-3xl hover:bg-white/[0.04] transition-colors">
            <div className="w-16 h-16 bg-gradient-to-b from-blue-500/20 via-blue-500/5 to-blue-500/20 text-blue-400 rounded-2xl flex items-center justify-center mb-6">
              <TerminalSquare className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-medium text-white mb-3">Robust Scripting</h3>
            <p className="text-gray-400 font-light text-sm leading-relaxed">Write clean, modular, and fault-tolerant scripts. Deal with error handling, API ratelimits, and unstructured datasets efficiently.</p>
          </div>

          <div className="flex flex-col items-center text-center p-8 bg-gradient-to-b from-blue-500/5 via-[#050814] to-[#0a0f24] rounded-3xl hover:bg-white/[0.04] transition-colors">
            <div className="w-16 h-16 bg-gradient-to-b from-purple-500/20 via-purple-500/5 to-purple-500/20 text-purple-400 rounded-2xl flex items-center justify-center mb-6">
              <DatabaseZap className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-medium text-white mb-3">Pipeline Engineering</h3>
            <p className="text-gray-400 font-light text-sm leading-relaxed">Design logical workflows that transform raw inputs into structured outputs quickly, reducing manual labor processing times drastically.</p>
          </div>

          <div className="flex flex-col items-center text-center p-8 bg-gradient-to-b from-blue-500/5 via-[#050814] to-[#0a0f24] rounded-3xl hover:bg-white/[0.04] transition-colors">
            <div className="w-16 h-16 bg-gradient-to-b from-emerald-500/20 via-emerald-500/5 to-emerald-500/20 text-emerald-400 rounded-2xl flex items-center justify-center mb-6">
              <TrendingUp className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-medium text-white mb-3">Scaling & Optimization</h3>
            <p className="text-gray-400 font-light text-sm leading-relaxed">It's not just about getting it to work once; it's about processing 1,000,000 rows as efficiently as 100 rows. Optimize your logic.</p>
          </div>
        </div>
      </section>

      {/* Track Requirements */}
      <section className="py-24 bg-gradient-to-b from-black via-[#050814] to-[#0a0f24]">
        <div className="max-w-5xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-semibold md:text-5xl font-light text-white mb-4">Final Submission (Mandatory Outputs)</h2>
            <p className="text-gray-400 font-light max-w-3xl mx-auto leading-relaxed">Participants must submit the following four components, compressed into a single .zip file. Non-compliance with formatting requirements will result in point deductions.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
            {requirements.map((req, idx) => (
              <div key={idx} className={`relative flex flex-col bg-white/[0.02] rounded-3xl p-8 transition-transform duration-300 group hover:shadow-[0_0_20px_rgba(59,130,246,0.15)] h-full`}>
                <h3 className={`text-xl font-semibold mb-3 text-blue-400`}>{req.title}</h3>
                <p className="text-gray-300 font-light text-sm mb-4 leading-relaxed">{req.desc}</p>
                
                <div className="flex flex-col gap-3 flex-1">
                  {req.bullets.map((bullet, bIdx) => (
                    <div key={bIdx} className="flex items-start gap-3 text-sm font-light">
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-2 shrink-0" />
                      <span className="text-gray-400 leading-relaxed">{bullet}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
